swagger: "2.0"
info:
  description: "This API offers the information of the Products listed in the database."
  version: "1.0.0"
  title: "Swagger Walmart Project"
  contact:
    email: "denissecasteletti@gmail.com"
host: "localhost:3001"
basePath: "/v1"
paths:
  /products/{id}:
    get:
      tags:
        - "Products"
      summary: "Find pet by ID"
      description: "Get the products by the id granted."
      operationId: "getPetById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of pet to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "valid response"
          schema:
            $ref: '#/components/schemas/Product'
        "400":
          description: "invalid response"
        "404":
          description: "invalid response"
components:
  schemas:
    Product:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          brand:
            type: string
            example: Walmart
          description:
            type: string
            example: TV
          image:
            type: string
            example: www.walmart.cl/image/1
          price:
            type: integer
            format: int64
            example: 1
